name: CD
on: [workflow_dispatch]
jobs:
  # This workflow contain a single job called "hello"
  hello:
    # the type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of talks that will be execcuted as part of the jobs
    steps:
    - name: helloweurldz
      run: echo 'Hello simplonz'